# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    relay: "#{source_dir}"
  forge_modules:
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.0.0"
#     stdlib: "puppetlabs/stdlib"
